#!perl
use Cassandane::Tiny;

sub test_mailbox_querychanges_max_changes
    ($self)
{
    my $user = $self->default_user;
    my $jmap = $user->jmap;

    my $sort = [{ property => 'name' }];

    my $state = $jmap->request([[ 'Mailbox/query', { sort => $sort } ]])
                     ->single_sentence('Mailbox/query')
                     ->arguments->{queryState};

    $user->mailboxes->create({ name => 'A' });
    $user->mailboxes->create({ name => 'B' });

    my $res = $jmap->request([[ 'Mailbox/queryChanges', {
        sinceQueryState => $state,
        sort            => $sort,
        maxChanges      => 1,
    } ]]);
    $self->assert_str_equals('tooManyChanges',
        $res->single_sentence('error')->arguments->{type});

    $res = $jmap->request([[ 'Mailbox/queryChanges', {
        sinceQueryState => $state,
        sort            => $sort,
        maxChanges      => 2,
    } ]]);
    $self->assert_num_equals(2, scalar @{
        $res->single_sentence('Mailbox/queryChanges')->arguments->{added}
    });
}
