#!perl
use Cassandane::Tiny;

# Share a folder with the '1' (ACL_AUTOSUB) right, and give cassandane a
# folder of its own subscribed the ordinary way, for the merge/dedup case.
sub setup_list_autosub ($self)
{
    my $admintalk = $self->{adminstore}->get_client();
    my $imaptalk  = $self->{store}->get_client();

    $admintalk->create("user.otheruser.autoshared") or die "create: $@";
    $admintalk->setacl("user.otheruser.autoshared", "group:group co", "lrs1")
        or die "setacl: $@";

    $imaptalk->create("INBOX.mine") or die "create: $@";
    $imaptalk->subscribe("INBOX.mine") or die "subscribe: $@";

    return $imaptalk;
}

# assert_mailbox_structure() indexes responses by name, so a duplicated
# response would collapse and go unnoticed -- count them first, since not
# duplicating the merged-in mailboxes is the point of these tests.
sub assert_list_autosub ($self, $data, $expected, $msg)
{
    my %count;
    $count{ $_->[2] }++ for $data->@*;
    my @dupes = grep {; $count{$_} > 1 } sort keys %count;
    $self->assert_num_equals(0, scalar @dupes, "duplicated in LIST: @dupes");

    $self->assert_mailbox_structure($data, '.', $expected, 0, $msg);
}

sub test_list_autosub_subscribed
    :NoAltNamespace
    ($self)
{
    my $imaptalk = $self->setup_list_autosub;

    xlog $self, "subscribe the shared folder for real as well";
    $imaptalk->subscribe("user.otheruser.autoshared") or die "subscribe: $@";

    my $subscribed = $imaptalk->list([qw(SUBSCRIBED)], "", "*");

    $self->assert_list_autosub(
        $subscribed,
        {
            'INBOX.mine' => [ '\\Subscribed' ],
            'user.otheruser.autoshared' => [ '\\Subscribed' ],
        },
        "LIST (SUBSCRIBED) shows the real and the flag-granted subscription",
    );
}

sub test_list_autosub_after_unsubscribe
    :NoAltNamespace
    ($self)
{
    my $imaptalk = $self->setup_list_autosub;

    xlog $self, "unsubscribing the flag-granted folder succeeds";
    $imaptalk->subscribe("user.otheruser.autoshared") or die "subscribe: $@";
    $imaptalk->unsubscribe("user.otheruser.autoshared")
        or die "unsubscribe: $@";

    my $subscribed = $imaptalk->list([qw(SUBSCRIBED)], "", "*");
    my $lsub = $imaptalk->lsub("", "*");
    my $returned = $imaptalk->list([qw()], "", "*", 'RETURN', [qw(SUBSCRIBED)]);

    $self->assert_list_autosub(
        $subscribed,
        {
            'INBOX.mine' => [ '\\Subscribed' ],
            'user.otheruser.autoshared' => [ '\\Subscribed' ],
        },
        "... but the folder stays listed via the flag",
    );

    $self->assert_list_autosub(
        $lsub,
        {
            'INBOX.mine' => [],
            'user.otheruser.autoshared' => [],
        },
        "LSUB shows it too",
    );

    $self->assert_list_autosub(
        $returned,
        {
            'INBOX' => [],
            'INBOX.mine' => [ '\\Subscribed' ],
            'user.otheruser.autoshared' => [ '\\Subscribed' ],
        },
        "RETURN (SUBSCRIBED) annotates the flag-granted folder",
    );
}
