#!perl
use Cassandane::Tiny;

sub test_email_query_sort_keyword_required
    :JMAPExtensions
    ($self)
{
    my $jmap = $self->default_user->jmap;

    my $query_state = $jmap->request([
        [ 'Email/query', { sort => [ { property => 'receivedAt' } ] }, 'R1' ],
    ])->single_sentence('Email/query')->arguments->{queryState};

    # RFC 8621 4.4.2: these comparators MUST have a valid keyword
    for my $property (qw( hasKeyword someInThreadHaveKeyword )) {
        for my $keyword (undef, '', 'bad keyword', JSON::true) {
            my $sort = [
                { property => 'receivedAt' },
                { property => $property,
                  defined $keyword ? (keyword => $keyword) : () },
            ];

            my $res = $jmap->request([
                [ 'Email/query', { sort => $sort }, 'query' ],
                [ 'Email/queryChanges', { sort            => $sort,
                                          sinceQueryState => $query_state },
                  'querychanges' ],
            ]);

            for my $method (qw( query querychanges )) {
                my $args = $res->paragraph_by_client_id($method)
                               ->single('error')->arguments;
                $self->assert_cmp_deeply(
                    { type => 'invalidArguments', arguments => [ 'sort[1]' ] },
                    $args,
                    "$method $property keyword "
                        . ($keyword // 'missing'),
                );
            }
        }
    }
}
