#!perl
use Cassandane::Tiny;

sub test_email_get_rfc8621_values
    ($self)
{
    my $jmap = $self->default_user->jmap;
    my $imap = $self->{store}->get_client();

    my $raw = <<'EOF';
From: sender@example.com
To: =?UTF-8?B?R3LDvHBwZQ==?=: ann@example.com;
Subject: values
Message-ID: <msg@example.com>
In-Reply-To: not a message id
X-Refs: <a@example.com> (comment) <b@example.com>
Date: Mon, 13 Apr 2026 15:34:03 +0200
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary=b

--b
Content-Type: text/plain; charset=us-ascii

good
--b
Content-Type: text/plain; charset=x-jmts-unknown

unknown charset
--b--
EOF
    $raw =~ s/\r?\n/\r\n/gs;
    $imap->append('INBOX', $raw) || die $@;

    my $id = $jmap->request([[ 'Email/query', {} ]])
                  ->single_sentence('Email/query')->arguments->{ids}[0];

    my $email = $jmap->request([[ 'Email/get', {
        ids => [ $id ],
        properties => [
            'bodyValues', 'inReplyTo',
            'header:To:asGroupedAddresses',
            'header:X-Refs:asMessageIds',
        ],
        fetchAllBodyValues => JSON::true,
        maxBodyValueBytes  => 0,
    } ]])->single_sentence('Email/get')->arguments->{list}[0];

    $self->assert_cmp_deeply({
        id => $id,
        # RFC 8621 4.2: maxBodyValueBytes 0 means no truncation
        # RFC 8621 4.1.4: an unknown charset is an encoding problem
        bodyValues => {
            1 => superhashof({ value => "good",
                               isEncodingProblem => JSON::false,
                               isTruncated => JSON::false }),
            2 => superhashof({ isEncodingProblem => JSON::true,
                               isTruncated => JSON::false }),
        },
        # RFC 8621 4.1.2.5: if parsing fails, the value is null.  We
        # accept one id without brackets, but not several.
        inReplyTo => undef,
        # CFWS between msg-ids is allowed
        'header:X-Refs:asMessageIds' => [ 'a@example.com', 'b@example.com' ],
        # RFC 8621 4.1.2.4: encoded words in a group name are decoded
        'header:To:asGroupedAddresses' => [ {
            name => "Gr\N{U+00FC}ppe",
            addresses => [ { name => undef, email => 'ann@example.com' } ],
        } ],
    }, $email);
}
