#!perl
use Cassandane::Tiny;
use DateTime;

sub test_emailsubmission_set_max_delayed_send
    :needs_component_calalarmd :NoStartInstances
    ($self)
{
    $self->config_set(jmap_max_delayed_send => '1h');
    $self->_start_instances();
    $self->_setup_http_service_objects();

    my $jmap = $self->{jmap};

    my $res = $jmap->CallMethods([[ 'Identity/get', {}, "R1" ]]);
    my $identityid = $res->[0][1]{list}[0]{id};

    $self->make_message("foo", body => "an email\r\n") or die;
    $res = $jmap->CallMethods([[ 'Email/query', {}, "R1" ]]);
    my $emailid = $res->[0][1]{ids}[0];

    my $until = sub ($secs) {
        DateTime->from_epoch(epoch => time + $secs)->strftime('%Y-%m-%dT%H:%M:%SZ');
    };

    my %params = (
        holdfor_max      => { HOLDFOR   => '3600' },
        holdfor_over     => { HOLDFOR   => '3601' },
        holduntil_within => { HOLDUNTIL => $until->(3000) },
        holduntil_over   => { HOLDUNTIL => $until->(7200) },
    );

    $res = $jmap->CallMethods([[ 'EmailSubmission/set', {
        create => {
            map {
                $_ => {
                    identityId => $identityid,
                    emailId    => $emailid,
                    envelope   => {
                        mailFrom => {
                            email      => 'from@localhost',
                            parameters => $params{$_},
                        },
                        rcptTo => [ { email => 'rcpt@localhost' } ],
                    },
                },
            } keys %params
        },
    }, "R1" ]]);

    $self->assert_cmp_deeply(
        bag(qw( holdfor_max holduntil_within )),
        [ keys %{$res->[0][1]{created}} ],
    );
    $self->assert_cmp_deeply(
        {
            holdfor_over => {
                type       => 'invalidProperties',
                properties => [ 'envelope/mailFrom/parameters/HOLDFOR' ],
            },
            holduntil_over => {
                type       => 'invalidProperties',
                properties => [ 'envelope/mailFrom/parameters/HOLDUNTIL' ],
            },
        },
        $res->[0][1]{notCreated},
    );
}
