name: Content linting

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  content-linting:
    name: Content linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Assert no tabs
      shell: bash
      run: ./tools/hard-tab-tool
    - name: Assert no FIXME
      shell: bash
      run: ./tools/find-fixme-markers
